/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockFactoryCreatedPool,
  MockFactoryCreatedPoolInterface,
} from "../MockFactoryCreatedPool";

const _abi = [
  {
    inputs: [],
    name: "getPoolId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50608a8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806338fff2d014602d575b600080fd5b60336047565b604051603e9190604b565b60405180910390f35b3090565b9081526020019056fea26469706673582212204e4002aaf6a5776b600e6299291cee759f817cd82aba96e76df8ed5e524122cb64736f6c63430007010033";

type MockFactoryCreatedPoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockFactoryCreatedPoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockFactoryCreatedPool__factory extends ContractFactory {
  constructor(...args: MockFactoryCreatedPoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockFactoryCreatedPool> {
    return super.deploy(overrides || {}) as Promise<MockFactoryCreatedPool>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MockFactoryCreatedPool {
    return super.attach(address) as MockFactoryCreatedPool;
  }
  connect(signer: Signer): MockFactoryCreatedPool__factory {
    return super.connect(signer) as MockFactoryCreatedPool__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockFactoryCreatedPoolInterface {
    return new utils.Interface(_abi) as MockFactoryCreatedPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockFactoryCreatedPool {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockFactoryCreatedPool;
  }
}
