/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockPoolFactory,
  MockPoolFactoryInterface,
} from "../MockPoolFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IVault",
        name: "_vault",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "PoolCreated",
    type: "event",
  },
  {
    inputs: [],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getVault",
    outputs: [
      {
        internalType: "contract IVault",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "isPoolFromFactory",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161036d38038061036d83398101604081905261002f91610044565b60601b6001600160601b031916608052610072565b600060208284031215610055578081fd5b81516001600160a01b038116811461006b578182fd5b9392505050565b60805160601c6102df61008e6000398060b952506102df6000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80636634b753146100465780638d928af81461006f578063efc81a8c14610084575b600080fd5b61005961005436600461019a565b61008c565b60405161006691906101f6565b60405180910390f35b6100776100b7565b60405161006691906101d5565b6100776100db565b73ffffffffffffffffffffffffffffffffffffffff1660009081526020819052604090205460ff1690565b7f000000000000000000000000000000000000000000000000000000000000000090565b6000806040516100ea9061018e565b604051809103906000f080158015610106573d6000803e3d6000fd5b50905061011281610117565b905090565b73ffffffffffffffffffffffffffffffffffffffff811660008181526020819052604080822080547fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00166001179055517f83a48fbcfc991335314e74d0496aab6a1987e992ddc85dddbcc4d6dd6ef2e9fc9190a250565b60a88061020283390190565b6000602082840312156101ab578081fd5b813573ffffffffffffffffffffffffffffffffffffffff811681146101ce578182fd5b9392505050565b73ffffffffffffffffffffffffffffffffffffffff91909116815260200190565b90151581526020019056fe6080604052348015600f57600080fd5b50608a8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806338fff2d014602d575b600080fd5b60336047565b604051603e9190604b565b60405180910390f35b3090565b9081526020019056fea26469706673582212204e4002aaf6a5776b600e6299291cee759f817cd82aba96e76df8ed5e524122cb64736f6c63430007010033a26469706673582212204dd507f788c45faf25f93a8e50251ec42470753131cc1dbdc18898b68ce1b23964736f6c63430007010033";

type MockPoolFactoryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPoolFactoryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPoolFactory__factory extends ContractFactory {
  constructor(...args: MockPoolFactoryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    _vault: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockPoolFactory> {
    return super.deploy(_vault, overrides || {}) as Promise<MockPoolFactory>;
  }
  getDeployTransaction(
    _vault: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_vault, overrides || {});
  }
  attach(address: string): MockPoolFactory {
    return super.attach(address) as MockPoolFactory;
  }
  connect(signer: Signer): MockPoolFactory__factory {
    return super.connect(signer) as MockPoolFactory__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPoolFactoryInterface {
    return new utils.Interface(_abi) as MockPoolFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockPoolFactory {
    return new Contract(address, _abi, signerOrProvider) as MockPoolFactory;
  }
}
