/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IDeploymentValidatorInterface extends ethers.utils.Interface {
  functions: {
    "checkPairValidation(address,address)": FunctionFragment;
    "checkPoolValidation(address)": FunctionFragment;
    "checkWPValidation(address)": FunctionFragment;
    "validateAddresses(address,address)": FunctionFragment;
    "validatePoolAddress(address)": FunctionFragment;
    "validateWPAddress(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkPairValidation",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkPoolValidation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkWPValidation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateAddresses",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "validatePoolAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateWPAddress",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkPairValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkPoolValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkWPValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatePoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateWPAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IDeploymentValidator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDeploymentValidatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkPairValidation(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "checkPairValidation(address,address)"(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    checkPoolValidation(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "checkPoolValidation(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    checkWPValidation(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "checkWPValidation(address)"(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    validateAddresses(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "validateAddresses(address,address)"(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validatePoolAddress(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "validatePoolAddress(address)"(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateWPAddress(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "validateWPAddress(address)"(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  checkPairValidation(
    wrappedPosition: string,
    pool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "checkPairValidation(address,address)"(
    wrappedPosition: string,
    pool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  checkPoolValidation(
    pool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "checkPoolValidation(address)"(
    pool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  checkWPValidation(
    wrappedPosition: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "checkWPValidation(address)"(
    wrappedPosition: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  validateAddresses(
    wrappedPosition: string,
    pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "validateAddresses(address,address)"(
    wrappedPosition: string,
    pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validatePoolAddress(
    pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "validatePoolAddress(address)"(
    pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateWPAddress(
    wrappedPosition: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "validateWPAddress(address)"(
    wrappedPosition: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkPairValidation(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "checkPairValidation(address,address)"(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkPoolValidation(
      pool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "checkPoolValidation(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkWPValidation(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "checkWPValidation(address)"(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    validateAddresses(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "validateAddresses(address,address)"(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    validatePoolAddress(pool: string, overrides?: CallOverrides): Promise<void>;

    "validatePoolAddress(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    validateWPAddress(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "validateWPAddress(address)"(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkPairValidation(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkPairValidation(address,address)"(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkPoolValidation(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkPoolValidation(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkWPValidation(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkWPValidation(address)"(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateAddresses(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "validateAddresses(address,address)"(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validatePoolAddress(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "validatePoolAddress(address)"(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateWPAddress(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "validateWPAddress(address)"(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkPairValidation(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkPairValidation(address,address)"(
      wrappedPosition: string,
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkPoolValidation(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkPoolValidation(address)"(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkWPValidation(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkWPValidation(address)"(
      wrappedPosition: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateAddresses(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "validateAddresses(address,address)"(
      wrappedPosition: string,
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validatePoolAddress(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "validatePoolAddress(address)"(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateWPAddress(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "validateWPAddress(address)"(
      wrappedPosition: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
